# Project Information
site_name: DF Team
site_description: DF Team CTF writeups
site_author: DF Team
site_url: https://A30lu5.github.io/blogs/

# Repository
repo_name: 'A30lu5/blogs'
repo_url: 'https://github.com/A30lu5/blogs'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 DF Team'

# Contents
nav:
  - Introduction:
    - Getting Started: index.md
    - noxCTF2018:
      - Pwn:
        - believe Me: noxCTF2018/pwn/believeMe/writeup.md
        - The Name Calculator: noxCTF2018/pwn/TheNameCalculator/writeup.md
        - Grocery List: noxCTF2018/pwn/GroceryList/writeup.md
        - The Black Canary: noxCTF2018/pwn/TheBlackCanary/writeup.md
      - reverse:
        - GuessTheString: noxCTF2018/reverse/GuessTheString/writeup.md
        - Att3nti0n: noxCTF2018/reverse/Att3nti0n/writeup.md
        - avatar: noxCTF2018/reverse/avatar/writeup.md
      - web:
        - Reference: noxCTF2018/web/Reference/writeup.md
        - MyFileUploader: noxCTF2018/web/MyFileUploader/writeup.md
        - hiddenDOM: noxCTF2018/web/hiddenDOM/writeup.md
      - misc:
        - Blind Date: noxCTF2018/misc/Blind_Date/writeup.md
        - Python_for_fun: noxCTF2018/misc/Python_for_fun/writeup.md
        - Python_for_fun_2: noxCTF2018/misc/Python_for_fun_2/writeup.md
        - Read_Between_The_Lines: noxCTF2018/misc/Read_Between_The_Lines/writeup.md
        - Slippery_Situation: noxCTF2018/misc/Slippery_Situation/writeup.md
      - crypto:
        - Chop_Suey: noxCTF2018/crypto/Chop_Suey/writeup.md
        - Decryptor: noxCTF2018/crypto/Decryptor/writeup.md
        - Java_Corporation: noxCTF2018/crypto/Java_Corporation/writeup.md
        - Plot_Twist: noxCTF2018/crypto/Plot_Twist/writeup.md
        - Trinity: noxCTF2018/crypto/Trinity/writeup.md
        - WTF: noxCTF2018/crypto/WTF/writeup.md
    - CSAW-CTF-2018-Quals:
      - Pwn:
        - bigboy | 简单栈溢出: CSAW-CTF-2018-Quals/pwn/bigboy/writeup.md
        - get it | 简单栈溢出:  CSAW-CTF-2018-Quals/pwn/get_it/writeup.md
        - shellpointcode | 13字节的shellcode: CSAW-CTF-2018-Quals/pwn/shellpointcode/writeup.md
        - doubletrouble | 双精度浮点排序: CSAW-CTF-2018-Quals/pwn/doubletrouble/writeup.md
        - turtles | objc对象构造: CSAW-CTF-2018-Quals/pwn/turtles/writeup.md
        - PLC | ret2syscall: CSAW-CTF-2018-Quals/pwn/plc/writeup.md
        - Alien Invasion | 数据越界: CSAW-CTF-2018-Quals/pwn/alien_invasion/writeup.md
    - Reverse:
        - A-Walk-Through-x86-Part-1: CSAW-CTF-2018-Quals/rev/A-Walk-Through-x86-Part-1/writeup.md
        - A-Walk-Through-x86-Part-2: CSAW-CTF-2018-Quals/rev/A-Walk-Through-x86-Part-2/writeup.md
        - A-Walk-Through-x86-Part-3: CSAW-CTF-2018-Quals/rev/A-Walk-Through-x86-Part-3/writeup.md
        - 1337: CSAW-CTF-2018-Quals/rev/1337/writeup.md
        - kvm: CSAW-CTF-2018-Quals/rev/kvm/writeup.md
      - Crypto:
        -  babycrypto : CSAW-CTF-2018-Quals/crypto/babycrypto/writeup.md
        -  flatcrypt : CSAW-CTF-2018-Quals/crypto/flatcrypt/writeup.md
        -  lowe : CSAW-CTF-2018-Quals/crypto/lowe/writeup.md
        -  holywater : CSAW-CTF-2018-Quals/crypto/holywater/writeup.md
        -  collusion : CSAW-CTF-2018-Quals/crypto/collusion/writeup.md
      - Misc:
        -  bin_t : CSAW-CTF-2018-Quals/misc/bin_t/writeup.md
        -  algebra : CSAW-CTF-2018-Quals/misc/algebra/writeup.md
        -  TakeAnL : CSAW-CTF-2018-Quals/misc/TakeAnL/writeup.md
        -  Short-Circuit : CSAW-CTF-2018-Quals/misc/Short-Circuit/writeup.md
      - Web:
        - ldab: CSAW-CTF-2018-Quals/web/ldab/README.md
        - movie_club: CSAW-CTF-2018-Quals/web/movie_club/writeup.md
        - nvs: CSAW-CTF-2018-Quals/web/nvs/README.md
        - sso: CSAW-CTF-2018-Quals/web/sso/writeup.md
        - wtf_sql: CSAW-CTF-2018-Quals/web/wtf_sql/writeup.md

 
# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'blogs'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
