services:
  the_end:
    build: .
    command: /start.sh
    image: 10.10.83.201:5001/challenges:the_end
    labels:
      '9999': nc IP PORT
    ports:
    - 9999:9999
    restart: unless-stopped
version: '3'
