services:
  slot_machine:
    build: .
    command: /start.sh
    image: 10.10.83.201:5001/challenges:slot_machine
    labels:
      '9999': nc IP PORT
    ports:
    - 9999:9999
    restart: unless-stopped
version: '3'
